### ISSUE TITLE
compatibility with API 9

### ISSUE THREAD

**Issue by ubeyou** [grandcentrix/tray#14]
> uses-sdk:minSdkVersion 9 cannot be smaller than version 15 declared in library

I'm wondering can It support a lower version

**Comment by passsy** [comment]
Thanks for the input. Never thought about the minSdkVersion. I think decreasing it to 11 shouldn't be a problem. 

There are two methods which require `minSdkVersion` 11. Just decrease the api level and run lint. You could work around those calls create a PullRequest and add the support for API level 9 ;) 

But honestly, I think buying every user a new phone who is still using gingerbread is the easiest solution.

**Comment by passsy** [comment]
I was thinking about this again. I came to the conclusion, that the current `minSdkVersion 15` is good. 

I guess no one is using `minSdkVersion 11` because there are no users using 11-14.
`minSdkVersion 9` is too low because this lib uses functions of API level 11.

My advice: Ask your product manager to drop support for Android 2.3 because using this awesome Tray library and would increase your productivity and would cause less bugs.

**Comment by LiHanGuang** [comment]
@ passsy
Can i use  minSdkVersion 14?
